#!/bin/bash

echo 'make sure u running this as root playa'

echo 'Enabling error display'
sudo sed -i -e 's/;display_errors = Off/display_errors = On/' /etc/php5/apache2/php.ini 
echo 'Enabling database logging'
sudo sed -i -e 's$#general_log_file        = /var/log/mysql/mysql.log$general_log_file        = /var/log/mysql/mysql.log$' /etc/mysql/my.cnf
sudo sed -i -e 's$#general_log             = 1$general_log             = 1$' /etc/mysql/my.cnf
echo 'Restarting sqldb...give it a sec pimp...should see it soon'
sudo systemctl restart mysql 
tail -f /var/log/mysql/mysql.log 
